use std::{
    fs::{self, OpenOptions},
    io::Write,
    path::Path,
};

use crate::{FrilVaultError, FrilVaultResult};

pub const AGENTS_FILE_NAME: &str = "AGENTS.md";
pub const AGENTS_TEMPLATE_VERSION: u32 = 1;

const AGENTS_TEMPLATE: &str = include_str!("../templates/vault-agents.md");

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AgentsFileStatus {
    Created,
    Preserved,
}

impl AgentsFileStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Preserved => "preserved",
        }
    }
}

pub(crate) fn ensure_agents_file(
    vault_root: impl AsRef<Path>,
) -> FrilVaultResult<AgentsFileStatus> {
    let path = vault_root.as_ref().join(AGENTS_FILE_NAME);

    if path.exists() {
        return if path.is_file() {
            Ok(AgentsFileStatus::Preserved)
        } else {
            Err(FrilVaultError::Io(std::io::Error::new(
                std::io::ErrorKind::AlreadyExists,
                format!("{} exists but is not a file", path.display()),
            )))
        };
    }

    create_agents_file(&path)
}

fn create_agents_file(path: &Path) -> FrilVaultResult<AgentsFileStatus> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)?;

    let temp_path = parent.join(format!(
        ".{}.tmp.{}",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or(AGENTS_FILE_NAME),
        uuid::Uuid::new_v4()
    ));

    let write_result = (|| -> std::io::Result<AgentsFileStatus> {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temp_path)?;
        file.write_all(rendered_template().as_bytes())?;
        file.sync_all()?;
        drop(file);

        match fs::hard_link(&temp_path, path) {
            Ok(()) => Ok(AgentsFileStatus::Created),
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
                if path.is_file() {
                    Ok(AgentsFileStatus::Preserved)
                } else {
                    Err(error)
                }
            }
            Err(error) => Err(error),
        }
    })();

    let cleanup_result = fs::remove_file(&temp_path);
    match (write_result, cleanup_result) {
        (Ok(status), Ok(())) => Ok(status),
        (Ok(_status), Err(error)) => Err(FrilVaultError::Io(error)),
        (Err(error), _) => Err(FrilVaultError::Io(error)),
    }
}

fn rendered_template() -> String {
    AGENTS_TEMPLATE
        .replace("{{TEMPLATE_VERSION}}", &AGENTS_TEMPLATE_VERSION.to_string())
        .replace("{{FRILVAULT_VERSION}}", env!("CARGO_PKG_VERSION"))
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::{Path, PathBuf},
    };

    use super::*;

    struct TempDirectory(PathBuf);

    impl TempDirectory {
        fn new() -> Self {
            let path =
                std::env::temp_dir().join(format!("frilvault-agents-{}", uuid::Uuid::new_v4()));
            fs::create_dir_all(&path).unwrap();
            Self(path)
        }

        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for TempDirectory {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn creates_the_bundled_template_once() {
        let directory = TempDirectory::new();

        assert_eq!(
            ensure_agents_file(directory.path()).unwrap(),
            AgentsFileStatus::Created
        );

        let path = directory.path().join(AGENTS_FILE_NAME);
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("<!-- FrilVault AGENTS template version: 1 -->"));
        assert!(content.contains("Generated by FrilVault v"));
        assert!(!content.contains("{{"));
        assert_eq!(
            fs::read_dir(directory.path()).unwrap().count(),
            1,
            "temporary files must not remain after creation"
        );
    }

    #[test]
    fn preserves_existing_content_without_replacing_it() {
        let directory = TempDirectory::new();
        let path = directory.path().join(AGENTS_FILE_NAME);
        let custom_content = "# User instructions\nKeep this file unchanged.\n";
        fs::write(&path, custom_content).unwrap();

        assert_eq!(
            ensure_agents_file(directory.path()).unwrap(),
            AgentsFileStatus::Preserved
        );
        assert_eq!(fs::read_to_string(path).unwrap(), custom_content);
    }
}
